# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# - task: Docker@2
#   inputs:
#     containerRegistry: 'devopspipeline'
#     repository: 'patrickgovus/devops-app'
#     command: 'buildAndPush'
#     Dockerfile: '**/Dockerfile'

- bash: |
    echo "Using an input-macro works: $(mySecret)"

  env:
    MY_MAPPED_ENV_VAR: $(mySecret)

# - task: KubernetesManifest@1
#   inputs:
#     action: 'deploy'
#     connectionType: 'azureResourceManager'
#     azureSubscriptionConnection: 'test321'
#     azureResourceGroup: 'patrick-devops'
#     kubernetesCluster: 'patrickaks'
#     manifests: 'application-manifest.yaml'