# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'devopspipeline'
    repository: 'patrickgovus/devops-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

# - task: KubernetesManifest@1
#   inputs:
#     action: 'deploy'
#     connectionType: 'azureResourceManager'
#     azureSubscriptionConnection: 'Content Team(62974f8c-157b-47a7-918d-d076da5ee1e4)'
#     azureResourceGroup: 'patrick-devops'
#     kubernetesCluster: 'patrickaks'
#     manifests: '- task: KubernetesManifest@1
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'test123'
    azureResourceGroup: 'patrick-devops'
    kubernetesCluster: 'patrickaks'
    manifests: 'application-manifest.yaml'

# - task: KubernetesManifest@1
#   inputs:
#     action: 'deploy'
#     connectionType: 'azureResourceManager'
#     azureSubscriptionConnection: 'Content Team(62974f8c-157b-47a7-918d-d076da5ee1e4)'
#     azureResourceGroup: 'patrick-devops'
#     kubernetesCluster: 'patrickaks'
#     manifests: 'application-manifest.yaml'